### ISSUE TITLE
七五三が祝日に・・

### ISSUE THREAD

**Issue by sebon77** [holidays-jp/holidays-jp.github.io#2]
便利に使わせていただいております。

11月15日の七五三が祝日として上がってくるためにお客さんから指摘を受けました。

Googleカレンダーの設定問題のようですのでこちらのAPIがどういった形でGoogleから取得しているのかわかりませんが
通常のGoogleカレンダー画面ですと
「設定>他のカレンダーの設定>日本の祝日>祝日のみ」
の設定で直せるようです。

修正お願いできませんでしょうか？

**Comment by matsuoshi** [comment]
こちら、返信遅くなってすいません
以下で先に報告いただいており、対応済みのためクローズとさせていただきます
https://github.com/holidays-jp/api/issues/7
